#ifndef MMUL_BLAS_ASM_H
#define MMUL_BLAS_ASM_H

#include <map>
#include <string>
#include <vector>

static const std::vector<std::vector<std::string>> asmTable = [] {
  std::vector<std::vector<std::string>> table(
      27, std::vector<std::string>(16, "NOP"));
  table[0] = {"SADD ROUT, 2032, 0",
              "SADD ROUT, 2032, 0",
              "SADD ROUT, 2032, 0",
              "SADD ROUT, 2032, 0",
              "SADD ROUT, 2032, 0",
              "NOP",
              "NOP",
              "SADD ROUT, 2032, 0",
              "SADD ROUT, 2032, 0",
              "SADD ROUT, 2032, 0",
              "SADD ROUT, 2032, 0",
              "NOP",
              "NOP",
              "NOP",
              "SADD ROUT, 2032, 0",
              "NOP"};
  table[1] = {"SLT ROUT, ROUT, 5",
              "SLT ROUT, ROUT, 5",
              "SLT R0, ROUT, 5",
              "SLT ROUT, ROUT, 5",
              "SLT R0, ROUT, 5",
              "NOP",
              "NOP",
              "SLT ROUT, ROUT, 5",
              "SLT ROUT, ROUT, 5",
              "SLT R1, ROUT, 5",
              "SLT ROUT, ROUT, 5",
              "NOP",
              "NOP",
              "NOP",
              "SLT ROUT, ROUT, 5",
              "NOP"};
  table[2] = {"SADD R0, ROUT,4",
              "SADD R0, ROUT,4",
              "SADD R1, R0,12",
              "SADD R0, ROUT,16",
              "SADD R1, R0,8",
              "NOP",
              "NOP",
              "SADD R0, ROUT,8",
              "SADD R0, ROUT,20",
              "SADD R0, R1,16",
              "SADD R0, ROUT,20",
              "NOP",
              "NOP",
              "NOP",
              "SADD R0, ROUT,4",
              "NOP"};
  table[3] = {"NOP", "NOP", "LWI ROUT, R1", "LWI ROUT, R0", "LWI R2, R1", "NOP",
              "NOP", "NOP", "LWI R2, R0",   "LWI R2, R0",   "LWI R2, R0", "NOP",
              "NOP", "NOP", "NOP",          "NOP"};
  table[4] = {"NOP", "NOP",
              "NOP", "NOP",
              "NOP", "NOP",
              "NOP", "SADD ROUT, RCT, 0",
              "NOP", "SADD ROUT, RCL, 0",
              "NOP", "NOP",
              "NOP", "SADD ROUT, RCT, 0",
              "NOP", "NOP"};
  table[5] = {"NOP",
              "SADD R1, RCT, 0",
              "NOP",
              "NOP",
              "NOP",
              "SMUL R1, RCB, -4",
              "SADD R1, RCR, 0",
              "LWI R2, R0",
              "NOP",
              "LWI R2, R0",
              "NOP",
              "SADD R1, RCT, 0",
              "SADD R1, RCR, 0",
              "NOP",
              "NOP",
              "NOP"};
  table[6] = {"SADD ROUT, RCB,0",
              "LWI ROUT, R0",
              "NOP",
              "LWI ROUT, R0",
              "SADD R2, RCB,0",
              "NOP",
              "SMUL R2, RCB, 4",
              "NOP",
              "SMUL R2, RCR, 8",
              "LWI ROUT, R1",
              "SMUL R1, ROUT,-4",
              "SMUL R2, RCL, 8",
              "SMUL R2, RCT, 12",
              "SMUL R2, RCT, 12",
              "SADD R2, RCT, 0",
              "NOP"};
  table[7] = {"SMUL R1, RCB,-4",
              "SADD R2, RCL, 4",
              "NOP",
              "SADD R2, RCL, 0",
              "LWI ROUT, R0",
              "SADD R2, RCT, 4",
              "SADD R2, R2, RCR",
              "SMUL R2, RCT, 4",
              "SADD R2, R2, RCR",
              "SADD R1, ZERO, ZERO",
              "NOP",
              "SADD R2, R2, RCT",
              "SADD R2, R2, RCB",
              "SADD R2, R2, RCT",
              "LWI ROUT, R0",
              "SMUL R1, RCL, -4"};
  table[8] = {"LWI R2, R0",    "NOP", "LWI R2, R0",     "SRA R2, R2, 2",
              "SRA R2, R2, 2", "NOP", "SADD R2, R2, 8", "SADD R2, R2, RCR",
              "NOP",           "NOP", "SADD R2, RCB,8", "SADD R2, R2, 12",
              "NOP",           "NOP", "SRA R2, R2, 2",  "SADD R2, RCL,12"};
  table[9] = {"NOP",
              "NOP",
              "NOP",
              "SADD R1, ZERO, ZERO",
              "SADD R1, ZERO, ZERO",
              "NOP",
              "NOP",
              "NOP",
              "NOP",
              "NOP",
              "NOP",
              "NOP",
              "NOP",
              "NOP",
              "NOP",
              "NOP"};
  table[10] = {
      "SADD R3, ZERO, ZERO", "SADD R3, ZERO, ZERO", "SADD R3, ZERO, ZERO",
      "SADD R3, ZERO, ZERO", "SADD R3, ZERO, ZERO", "SADD R3, ZERO, ZERO",
      "SADD R3, ZERO, ZERO", "SADD R3, ZERO, ZERO", "SADD R3, ZERO, ZERO",
      "SADD R3, ZERO, ZERO", "SADD R3, ZERO, ZERO", "SADD R3, ZERO, ZERO",
      "SADD R3, ZERO, ZERO", "SADD R3, ZERO, ZERO", "SADD R3, ZERO, ZERO",
      "SADD R3, ZERO, ZERO"};
  table[11] = {
      "LWI R0, R2", "NOP", "LWI R0, R2", "NOP",        "NOP",
      "LWI R0, R2", "NOP", "LWI R0, R2", "LWI R0, R2", "SADD R1, R1, 1",
      "LWI R0, R2", "NOP", "NOP",        "LWI R0, R2", "NOP",
      "LWI R0, R2"};
  table[12] = {"NOP",
               "SADD R0, ZERO, RCB",
               "NOP",
               "SADD R0, ZERO, RCL",
               "SADD R0, ZERO, RCL",
               "NOP",
               "SADD R0, ZERO, RCB",
               "NOP",
               "NOP",
               "SADD R0, ZERO, RCL",
               "NOP",
               "SADD R0, ZERO, RCB",
               "SADD R0, ZERO, RCB",
               "NOP",
               "SADD R0, ZERO, RCL",
               "NOP"};
  table[13] = {
      "SADD ROUT, ZERO, RCL", "SADD ROUT, ZERO, RCR", "SADD ROUT, ZERO, RCB",
      "SADD ROUT, ZERO, RCT", "SADD ROUT, ZERO, RCT", "SADD ROUT, ZERO, RCL",
      "SADD ROUT, ZERO, RCR", "SADD ROUT, ZERO, RCB", "SADD ROUT, ZERO, RCB",
      "SADD ROUT, ZERO, RCT", "SADD ROUT, ZERO, RCL", "SADD ROUT, ZERO, RCR",
      "SADD ROUT, ZERO, RCR", "SADD ROUT, ZERO, RCB", "SADD ROUT, ZERO, RCT",
      "SADD ROUT, ZERO, RCL"};
  table[14] = {
      "SMUL ROUT, R0, ROUT", "SMUL ROUT, R0, ROUT", "SMUL ROUT, R0, ROUT",
      "SMUL ROUT, R0, ROUT", "SMUL ROUT, R0, ROUT", "SMUL ROUT, R0, ROUT",
      "SMUL ROUT, R0, ROUT", "SMUL ROUT, R0, ROUT", "SMUL ROUT, R0, ROUT",
      "SMUL ROUT, R0, ROUT", "SMUL ROUT, R0, ROUT", "SMUL ROUT, R0, ROUT",
      "SMUL ROUT, R0, ROUT", "SMUL ROUT, R0, ROUT", "SMUL ROUT, R0, ROUT",
      "SMUL ROUT, R0, ROUT"};
  table[15] = {"SADD R3, R3, ROUT", "SADD R3, R3, ROUT", "SADD R3, R3, ROUT",
               "SADD R3, R3, ROUT", "SADD R3, R3, ROUT", "SADD R3, R3, ROUT",
               "SADD R3, R3, ROUT", "SADD R3, R3, ROUT", "SADD R3, R3, ROUT",
               "SADD R3, R3, ROUT", "SADD R3, R3, ROUT", "SADD R3, R3, ROUT",
               "SADD R3, R3, ROUT", "SADD R3, R3, ROUT", "SADD R3, R3, ROUT",
               "SADD R3, R3, ROUT"};
  table[16] = {"SSUB R2, R2, R1",
               "NOP",
               "SADD R2, R2, 4",
               "NOP",
               "NOP",
               "SSUB R2, R2, R1",
               "NOP",
               "SADD R2, R2, 4",
               "SADD R2, R2, 4",
               "BNE R1, R2, 11",
               "SSUB R2, R2, R1",
               "NOP",
               "NOP",
               "SADD R2, R2, 4",
               "NOP",
               "SSUB R2, R2, R1"};
  table[17] = {"NOP",
               "SADD ROUT, ZERO, R2",
               "NOP",
               "NOP",
               "SADD R1, R1, 1",
               "NOP",
               "SADD ROUT, ZERO, R2",
               "NOP",
               "NOP",
               "NOP",
               "NOP",
               "SADD ROUT, ZERO, R2",
               "SADD ROUT, ZERO, R2",
               "NOP",
               "NOP",
               "NOP"};
  table[18] = {"SADD ROUT, RCR, -4",
               "SADD R2, R2, 16",
               "SADD ROUT, RCL, 4",
               "NOP",
               "NOP",
               "SADD ROUT, RCR, -4",
               "SADD R2, R2, 16",
               "SADD ROUT, RCL, 4",
               "SADD ROUT, RCL, -12",
               "NOP",
               "SADD ROUT, RCR, -4",
               "SADD R2, R2, 16",
               "SADD R2, R2, 16",
               "SADD ROUT, RCL, 4",
               "NOP",
               "SADD ROUT, RCR, 12"};
  table[19] = {"NOP",
               "SADD ROUT, R2, -16",
               "NOP",
               "SADD ROUT, RCL, 4",
               "SADD ROUT, RCR, -4",
               "NOP",
               "SADD ROUT, R2, -16",
               "NOP",
               "NOP",
               "SADD ROUT, RCR, -4",
               "NOP",
               "SADD ROUT, R2, -16",
               "SADD ROUT, R2, -16",
               "NOP",
               "SADD ROUT, RCR, -4",
               "NOP"};
  table[20] = {"SWI R3, ROUT", "SWI R3, ROUT", "SWI R3, ROUT", "SWI R3, ROUT",
               "SWI R3, ROUT", "SWI R3, ROUT", "SWI R3, ROUT", "SWI R3, ROUT",
               "SWI R3, ROUT", "SWI R3, ROUT", "SWI R3, ROUT", "SWI R3, ROUT",
               "SWI R3, ROUT", "SWI R3, ROUT", "SWI R3, ROUT", "SWI R3, ROUT"};
  table[21] = {"SADD R2, R2, 16",
               "SADD ROUT, ZERO, R1",
               "NOP",
               "NOP",
               "NOP",
               "SADD R2, R2, 16",
               "SADD ROUT, ZERO, R1",
               "NOP",
               "NOP",
               "NOP",
               "SADD R2, R2, 16",
               "SADD ROUT, ZERO, R1",
               "SADD ROUT, ZERO, R1",
               "NOP",
               "NOP",
               "SADD R2, R2, 16"};
  table[22] = {"SMUL ROUT, RCR, R1",
               "NOP",
               "SMUL ROUT, RCL, -4",
               "NOP",
               "NOP",
               "SMUL ROUT, RCR, R1",
               "NOP",
               "SMUL ROUT, RCL, -4",
               "SMUL ROUT, RCL, -4",
               "SADD R1, ZERO, ZERO",
               "SMUL ROUT, RCR, R1",
               "NOP",
               "NOP",
               "SMUL ROUT, RCL, -4",
               "NOP",
               "SMUL ROUT, RCR, R1"};
  table[23] = {"SADD R2, R2, ROUT",
               "NOP",
               "SADD R2, R2, ROUT",
               "NOP",
               "BNE R1, R2, 10",
               "SADD R2, R2, ROUT",
               "NOP",
               "SADD R2, R2, ROUT",
               "SADD R2, R2, ROUT",
               "NOP",
               "SADD R2, R2, ROUT",
               "NOP",
               "NOP",
               "SADD R2, R2, ROUT",
               "NOP",
               "SADD R2, R2, ROUT"};
  table[24] = {"SMUL ROUT, R1, -4",
               "SMUL ROUT, R1, 16",
               "NOP",
               "SADD R1, R1, 1",
               "SMUL ROUT, R2, -16",
               "SMUL ROUT, R1, -4",
               "SMUL ROUT, R1, 16",
               "NOP",
               "NOP",
               "NOP",
               "SMUL ROUT, R1, -4",
               "SMUL ROUT, R1, 16",
               "SMUL ROUT, R1, 16",
               "NOP",
               "SMUL ROUT, R2, -16",
               "SMUL ROUT, R1, -4"};
  table[25] = {"SADD ROUT, ZERO, RCB",
               "SADD R2, R2, RCL",
               "SADD R2, R2, RCL",
               "NOP",
               "SADD R1, ZERO, ZERO",
               "SADD ROUT, ZERO, RCL",
               "SADD R2, R2, RCL",
               "SADD R2, R2, RCL",
               "SADD R2, R2, RCL",
               "NOP",
               "SADD ROUT, ZERO, RCB",
               "SADD R2, R2, RCL",
               "SADD R2, R2, RCL",
               "SADD R2, R2, RCL",
               "NOP",
               "SADD ROUT, ZERO, RCL"};
  table[26] = {"SADD R2, R2, ROUT",
               "SADD R2, R2, RCL",
               "NOP",
               "BNE R1, R2, 10",
               "NOP",
               "SADD R2, R2, ROUT",
               "SADD R2, R2, RCL",
               "NOP",
               "NOP",
               "NOP",
               "SADD R2, R2, ROUT",
               "SADD R2, R2, RCL",
               "SADD R2, R2, RCL",
               "NOP",
               "NOP",
               "SADD R2, R2, ROUT"};
  return table;
}();

struct ASMGenBLAS {
  int initPC = 0;

  ASMGenBLAS(int initPC) : initPC(initPC) {
    ctrl0 = "BNE R1, R2, " + std::to_string(initPC + 11);
    ctrl1 = "BNE R1, R2, " + std::to_string(initPC + 10);
  }

  std::vector<std::vector<std::string>> generatePreCompileCode() const {
    auto table = asmTable;
    table[16][9] = ctrl0;
    table[23][4] = ctrl1;
    table[26][3] = ctrl1;
    return table;
  }

  std::string ctrl0 = "BNE R1, R2, 11";
  std::string ctrl1 = "BNE R1, R2, 10";
};

#endif // MMUL_BLAS_ASM_H
