//===-  PolyhedraSchedule.cpp - Transform to catch mmul Pattern-*- C++ -*-===//
//
// Compigra is under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Implements functions to schedule statements in polyhedra model to catch mmul
// pattern.
//
//===----------------------------------------------------------------------===//

#include "compigra/Support/PolyhedraScheduler.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"

using namespace mlir;

bool isSinglePathStore(Value srcVal, affine::AffineStoreOp storeOp) {
  auto storeVal = storeOp.getValueToStore();
  // check whether storeVal is only generated by srcVal
  if (storeVal == srcVal)
    return true;

  // if srcVal undergoes a series of arithmetic operations with constants,
  // return true
  auto getSingleUser = [&](Value val) {
    auto users = val.getUsers();
    if (std::distance(users.begin(), users.end()) != 1)
      return (Operation *)nullptr;
    auto user = *users.begin();
    if (user->getNumResults() != 1)
      return (Operation *)nullptr;
    // check whether the other operands are constants
    for (auto operand : user->getOperands()) {
      if (operand != val) {
        if (!operand.getDefiningOp() ||
            !isa<arith::ConstantOp>(operand.getDefiningOp()))
          return (Operation *)nullptr;
      }
    }
    return user;
  };

  Operation *singleUser = getSingleUser(srcVal);
  while (singleUser) {
    if (singleUser->getResult(0) == storeVal)
      return true;
    singleUser = getSingleUser(singleUser->getResult(0));
  }
  return false;
}