//===-  PolyhedraSchedule.cpp - Transform to catch mmul Pattern-*- C++ -*-===//
//
// Compigra is under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Implements functions to schedule statements in polyhedra model to catch mmul
// pattern.
//
//===----------------------------------------------------------------------===//

#include "compigra/Support/PolyhedraScheduler.h"
#include "compigra/Support/Utils.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"

using namespace mlir;
using namespace mlir::affine;

bool isSinglePathStore(Value srcVal, affine::AffineStoreOp storeOp) {
  auto storeVal = storeOp.getValueToStore();
  // check whether storeVal is only generated by srcVal
  if (storeVal == srcVal)
    return true;

  // if srcVal undergoes a series of arithmetic operations with constants,
  // return true
  auto getSingleUser = [&](Value val) {
    auto users = val.getUsers();
    if (std::distance(users.begin(), users.end()) != 1)
      return (Operation *)nullptr;
    auto user = *users.begin();
    if (user->getNumResults() != 1)
      return (Operation *)nullptr;
    // check whether the other operands are constants
    for (auto operand : user->getOperands()) {
      if (operand != val) {
        if (!operand.getDefiningOp() ||
            !isa<arith::ConstantOp>(operand.getDefiningOp()))
          return (Operation *)nullptr;
      }
    }
    return user;
  };

  Operation *singleUser = getSingleUser(srcVal);
  while (singleUser) {
    if (singleUser->getResult(0) == storeVal)
      return true;
    singleUser = getSingleUser(singleUser->getResult(0));
  }
  return false;
}

void getAllStatements(affine::AffineForOp outerFor,
                      SetVector<Operation *> &statements) {
  outerFor.walk([&statements](mlir::Operation *op) {
    if (isa<affine::AffineLoadOp, affine::AffineStoreOp>(op))
      statements.insert(op);
  });
}

#ifdef HAVE_Z3
using namespace z3;

struct MemoryAccess {
  Operation *op;
  bool isLoad;
  std::vector<Value> indices;
  Value memref;
  int statementId;

  MemoryAccess(Operation *operation, bool load, Value mem, int stmtId)
      : op(operation), isLoad(load), memref(mem), statementId(stmtId) {}
};

struct StatementInfo {
  Operation *op;
  DenseMap<AffineForOp, std::pair<int, int>> bounds;
};

class ScheduleFunctionGenerator {
private:
  context ctx;
  solver s;
  std::vector<Operation *> statements;
  std::vector<MemoryAccess> memoryAccesses;
  AffineForOp rootLoop;
  // Ordered index of the loop iterators
  SmallVector<AffineForOp, 4> loops;
  DenseMap<int, StatementInfo> statementInfos;

  Operation *blasLoad1, *blasLoad2, *blasStore;
  int blasLoad1Id, blasLoad2Id, blasStoreId;

  // Schedule matrix: scheduleMatrix[stmtId][row][col]
  // Each statement has m rows (schedule dimensions) and n=4 columns (3 loops +
  // constant)
  std::map<std::tuple<int, int, int>, expr> scheduleMatrix;
  int numStatements;
  int numScheduleDimensions; // m - number of schedule dimensions (rows)
  int numLoopDimensions;     // n=4 - three loops + constant (columns)

public:
  ScheduleFunctionGenerator(AffineForOp rootLoop,
                            const SetVector<Operation *> &stmts,
                            int scheduleDims = 2)
      : rootLoop(rootLoop), s(ctx), numStatements(stmts.size()),
        numScheduleDimensions(scheduleDims), numLoopDimensions(4) {
    DenseMap<Operation *, std::pair<int, int>> bounds;
    rootLoop.walk([&](AffineForOp forOp) {
      auto lowerBound = forOp.getLowerBound().getMap();
      auto upperBound = forOp.getUpperBound().getMap();
      int lb = lowerBound.isSingleConstant()
                   ? lowerBound.getSingleConstantResult()
                   : 100;
      int ub = upperBound.isSingleConstant()
                   ? upperBound.getSingleConstantResult()
                   : 100;
      bounds[forOp] = {lb, ub};
      loops.insert(loops.begin(), forOp);
    });

    // Convert SetVector to std::vector
    for (Operation *op : stmts) {
      StatementInfo info;

      auto curBlock = op->getBlock();
      // Find all enclosing loops and their bounds
      while (curBlock) {
        if (auto forOp = dyn_cast<AffineForOp>(curBlock->getParentOp())) {
          if (bounds.find(forOp) != bounds.end())
            info.bounds[forOp] = bounds[forOp];
        }
        curBlock = curBlock->getParentOp() ? curBlock->getParentOp()->getBlock()
                                           : nullptr;
      }

      info.op = op;
      statementInfos[statements.size()] = info;
      statements.push_back(op);
    }

    // Initialize schedule matrix variables
    initializeScheduleMatrix();

    // Collect memory accesses
    collectMemoryAccesses();
  }

private:
  std::vector<std::vector<int>>
  generateIterationPoints(const std::vector<std::pair<int, int>> &bounds) {
    size_t k = bounds.size();
    std::vector<int> sizes(k);
    size_t total = 1;

    // Compute size of each dimension and total number of rows
    for (size_t i = 0; i < k; ++i) {
      int lower = bounds[i].first;
      int upper = bounds[i].second;
      if (lower > upper) {
        sizes[i] = 1; // column fixed to zero
      } else {
        sizes[i] = upper - lower + 1;
      }
      total *= sizes[i];
    }

    std::vector<std::vector<int>> result;
    result.reserve(total);

    // Generate combinations
    for (size_t idx = 0; idx < total; ++idx) {
      std::vector<int> row(k);
      size_t temp = idx;

      for (size_t j = 0; j < k; ++j) {
        int lower = bounds[j].first;
        int upper = bounds[j].second;

        if (lower > upper) {
          row[j] = 0;
        } else {
          int offset = temp % sizes[j];
          row[j] = lower + offset;
          temp /= sizes[j];
        }
      }
      result.push_back(std::move(row));
    }

    return result;
  }

  // Add lexicographic ordering constraint
  void addLexicographicConstraint(solver &s, const std::vector<expr> &vec1,
                                  const std::vector<expr> &vec2, bool strict) {
    expr result = ctx.bool_val(false);

    for (int i = 0; i < std::min(vec1.size(), vec2.size()); ++i) {
      expr prefixEqual = ctx.bool_val(true);

      // All previous dimensions are equal
      for (int j = 0; j < i; ++j) {
        prefixEqual = prefixEqual && (vec1[j] == vec2[j]);
      }

      // Current dimension: vec1[i] < vec2[i]
      expr currentLess = prefixEqual && (vec1[i] < vec2[i]);
      result = result || currentLess;
    }
    s.add(result == ctx.bool_val(true));
  };

public:
  void setBLASOps(Operation *load1, Operation *load2, Operation *store) {
    blasLoad1 = load1;
    blasLoad2 = load2;
    blasStore = store;

    auto getStatementId = [this](Operation *op) -> std::ptrdiff_t {
      auto it = std::find(statements.begin(), statements.end(), op);
      if (it != statements.end()) {
        return std::distance(statements.begin(), it);
      } else {
        return -1; // Not found
      }
    };

    blasLoad1Id = getStatementId(blasLoad1);
    blasLoad2Id = getStatementId(blasLoad2);
    blasStoreId = getStatementId(blasStore);
    llvm::errs() << "BLAS Load1 ID: " << blasLoad1Id << "\n";
    llvm::errs() << "BLAS Load2 ID: " << blasLoad2Id << "\n";
    llvm::errs() << "BLAS Store ID: " << blasStoreId << "\n";
  }

  expr getScheduleVar(int stmtId, int row, int col) {
    return scheduleMatrix.at({stmtId, row, col});
  }

  void initializeScheduleMatrix() {
    for (int stmtId = 0; stmtId < numStatements; ++stmtId) {
      for (int row = 0; row < numScheduleDimensions; ++row) {
        for (int col = 0; col < numLoopDimensions; ++col) {
          std::string varName = "theta_" + std::to_string(stmtId) + "_" +
                                std::to_string(row) + "_" + std::to_string(col);
          scheduleMatrix.emplace(std::make_tuple(stmtId, row, col),
                                 ctx.int_const(varName.c_str()));
        }
      }
    }
  }

  void collectMemoryAccesses() {
    for (int i = 0; i < statements.size(); ++i) {
      Operation *op = statements[i];

      if (auto loadOp = dyn_cast<AffineLoadOp>(op)) {
        MemoryAccess access(op, true, loadOp.getMemRef(), i);

        // Extract indices
        for (Value idx : loadOp.getIndices()) {
          access.indices.push_back(idx);
        }
        memoryAccesses.push_back(access);

      } else if (auto storeOp = dyn_cast<AffineStoreOp>(op)) {
        MemoryAccess access(op, false, storeOp.getMemRef(), i);

        // Extract indices
        for (Value idx : storeOp.getIndices()) {
          access.indices.push_back(idx);
        }
        memoryAccesses.push_back(access);
      }
    }
  }

  // Compute schedule vector for a statement at given iteration
  std::vector<expr>
  computeScheduleVector(int stmtId, const std::vector<expr> &iterationVector) {
    std::vector<expr> scheduleVector;

    for (int row = 0; row < numScheduleDimensions; ++row) {
      expr scheduleTime = ctx.int_val(0);

      // For each row: time = sum(theta[stmtId][row][col] *
      // iterationVector[col]) iterationVector should be [i1, i2, i3, 1] to
      // handle constant term
      for (int col = 0; col < numLoopDimensions; ++col) {
        scheduleTime = scheduleTime +
                       getScheduleVar(stmtId, row, col) * iterationVector[col];
      }
      scheduleVector.push_back(scheduleTime);
    }

    return scheduleVector;
  }

  // Get all iteration points for a statement based on its bounds
  std::vector<std::vector<int>> getAllIterationPoints(int stmtId) {
    auto it = statementInfos.find(stmtId);
    if (it == statementInfos.end()) {
      return {};
    }

    const StatementInfo &stmtInfo = it->second;

    // Extract bounds for each loop level
    std::vector<std::pair<int, int>> loopBounds;

    // Need to order the loops by nesting level
    // Assuming the bounds map is ordered by loop nesting depth
    for (auto loop : loops) {
      if (stmtInfo.bounds.find(loop) != stmtInfo.bounds.end()) {
        auto bounds = stmtInfo.bounds.lookup(loop);
        loopBounds.push_back(bounds);
      } else {
        // If the statement is outside this loop, fix the iteration to 0
        loopBounds.push_back({0, -1});
      }
    }
    // for (auto &boundPair : stmtInfo.bounds) {
    //   AffineForOp forOp = boundPair.first;
    //   std::pair<int, int> bounds = boundPair.second;
    //   loopBounds.push_back(bounds);
    // }

    // Generate all combinations of iteration points
    std::vector<std::vector<int>> iterationPoints =
        generateIterationPoints(loopBounds);

    return iterationPoints;
  }

  // Add universal constraints for all iteration points of two statements
  void addUniversalOrderingConstraint(int stmtId1, int stmtId2,
                                      bool strict = true) {
    auto points1 = getAllIterationPoints(stmtId1);
    auto points2 = getAllIterationPoints(stmtId2);

    // For each valid iteration point in the intersection of domains
    auto commonPoints = getCommonIterationPoints(points1, points2);

    for (const auto &iterPoint : commonPoints) {
      // Add constant term
      std::vector<expr> fullIterPoint;
      for (int val : iterPoint) {
        fullIterPoint.push_back(ctx.int_val(val));
      }

      fullIterPoint.push_back(ctx.int_val(1));

      auto schedule1 = computeScheduleVector(stmtId1, fullIterPoint);
      auto schedule2 = computeScheduleVector(stmtId2, fullIterPoint);

      // Add lexicographic constraint: schedule1 < schedule2 (or <=)
      addLexicographicConstraint(s, schedule1, schedule2, strict);
    }
  }

  // Get common iteration points between two statements
  std::vector<std::vector<int>>
  getCommonIterationPoints(std::vector<std::vector<int>> points1,
                           std::vector<std::vector<int>> points2) {
    if (points1.empty() || points2.empty())
      return {};

    std::vector<std::vector<int>> commonPoints;
    for (const auto &p : points1) {
      if (std::find(points2.begin(), points2.end(), p) != points2.end()) {
        commonPoints.push_back(p);
      }
    }
    return commonPoints;
  }

  // Example usage for your specific constraint: S0 < S1 < S2 < Sk
  void addOrderingConstraints() {
    for (auto [sId, info] : statementInfos) {
      for (auto [forOp, bounds] : info.bounds) {
        if (bounds.first > bounds.second)
          continue; 
        auto ivId = std::distance(loops.begin(),
                                  std::find(loops.begin(), loops.end(), forOp));
        s.add(getScheduleVar(sId, 1 + 2 * ivId, ivId) == 1);
      }
    }
    addUniversalOrderingConstraint(blasLoad1Id, blasLoad2Id, true);
    addUniversalOrderingConstraint(blasLoad2Id, blasStoreId, true);

    // Si < Sk for i ∈ {0,1,2}, k ≥ 3
    for (size_t i = 0; i < std::min(statements.size(), size_t(3)); ++i) {
      if (i == blasLoad1Id || i == blasLoad2Id || i == blasStoreId)
        continue;
      addUniversalOrderingConstraint(blasStoreId, i, true);
    }

    for (size_t i = 0; i < std::min(statements.size(), size_t(3)); ++i) {
      if (i == blasLoad1Id || i == blasLoad2Id || i == blasStoreId)
        continue;
      addUniversalOrderingConstraint(blasStoreId, i, true);
    }
  }

  void addSplitConstraints() {
    // For non-BLAS statements, Sk should be completely split to current scope
    int lastD = numLoopDimensions - 1;
    for (int k = 0; k < statements.size(); ++k) {
      if (k == blasLoad1Id || k == blasLoad2Id || k == blasStoreId)
        s.add(getScheduleVar(k, 0, lastD) == 0);
      else
        s.add(getScheduleVar(k, 0, lastD) >= 1);
    }
  }

  void addMemoryConsistencyConstraints() {
    // For each pair of memory accesses to the same address
    for (int i = 0; i < memoryAccesses.size(); ++i) {
      for (int j = i + 1; j < memoryAccesses.size(); ++j) {
        const MemoryAccess &access1 = memoryAccesses[i];
        const MemoryAccess &access2 = memoryAccesses[j];

        // Check if accessing the same memory location
        if (access1.memref == access2.memref &&
            accessesSameLocation(access1, access2)) {

          // Add dependence constraint
          if (createsDependence(access1, access2)) {
            llvm::errs() << "Dependence between statements "
                         << access1.statementId << " < " << access2.statementId
                         << "\n";

            addUniversalOrderingConstraint(access1.statementId,
                                           access2.statementId, true);
          }
        }
      }
    }

    for (int i = 0; i < statements.size(); ++i) {
      for (int j = 0; j < statements.size(); ++j) {
        if (i == j)
          continue;

        // Check if statements[i]'s result or its results' consumer are produced
        // by j
        if (compigra::consumesResult(statements[i], statements[j])) {
          llvm::errs() << "Dependency detected between statements " << i
                       << " < " << j << "\n";
          addUniversalOrderingConstraint(i, j, true);
        }
      }
    }
  }

  bool accessesSameLocation(const MemoryAccess &acc1,
                            const MemoryAccess &acc2) {
    // Simplified check - in practice, you'd need more sophisticated analysis
    return acc1.memref == acc2.memref &&
           acc1.indices.size() == acc2.indices.size();
  }

  bool createsDependence(const MemoryAccess &acc1, const MemoryAccess &acc2) {
    // True dependence: Read after Write
    // Anti-dependence: Write after Read
    // Output dependence: Write after Write
    return (!acc1.isLoad && acc2.isLoad) || // RAW
           (acc1.isLoad && !acc2.isLoad) || // WAR
           (!acc1.isLoad && !acc2.isLoad);  // WAW
  }

  void addBoundConstraints() {
    // Add reasonable bounds to avoid unbounded solutions
    for (int stmtId = 0; stmtId < numStatements; ++stmtId) {
      for (int row = 0; row < numScheduleDimensions; ++row) {
        for (int col = 0; col < numLoopDimensions; ++col) {
          s.add(getScheduleVar(stmtId, row, col) >= 0);
          if (col < numLoopDimensions - 1)
            s.add(getScheduleVar(stmtId, row, col) <= 1);
        }
      }
    }
  }

  void addRowSumConstraints() {
    // Ensure that for each statement, the sum of coefficients in each row is
    // at least 1
    for (int stmtId = 0; stmtId < numStatements; ++stmtId) {
      for (int col = 0; col < numLoopDimensions - 1; ++col) {
        expr rowSum = ctx.int_val(0);
        for (int row = 0; row < numScheduleDimensions; ++row) {
          rowSum = rowSum + getScheduleVar(stmtId, row, col);
        }
        s.add(rowSum <= 1);
      }
    }
  }

  void addColSumConstraints() {
    // Ensure that for each statement, the sum of coefficients in each row is
    // at least 1
    for (int stmtId = 0; stmtId < numStatements; ++stmtId) {
      for (int row = 1; row < numScheduleDimensions; row += 2) {
        expr colSum = ctx.int_val(0);
        for (int col = 0; col < numLoopDimensions; ++col) {
          colSum = colSum + getScheduleVar(stmtId, row, col);
        }
        s.add(colSum <= 1);
      }
    }
  }

  void addOptimizationGoal() {
    // Minimize the sum of absolute values of coefficients in even rows (rows
    // % 2 == 0)
    expr objective = ctx.int_val(0);

    for (int stmtId = 0; stmtId < numStatements; ++stmtId) {
      for (int row = 0; row < numScheduleDimensions; row += 2) {
        for (int col = 0; col < numLoopDimensions; ++col) {
          expr coeff = getScheduleVar(stmtId, row, col);

          // Add absolute value using auxiliary variables
          // expr absVar =
          //     ctx.int_const(("abs_" + std::to_string(stmtId) + "_" +
          //                    std::to_string(row) + "_" + std::to_string(col))
          //                       .c_str());

          // // Constraints for absolute value: absVar >= coeff and absVar >=
          // // -coeff
          // s.add(absVar >= coeff);
          // s.add(absVar >= -coeff);
          // s.add(absVar >= 0);

          // Add to objective
          objective = objective + coeff;
        }
      }
    }

    // Create optimizer and transfer constraints
    optimize opt(ctx);
    for (auto const &assertion : s.assertions()) {
      opt.add(assertion);
    }
    opt.minimize(objective);

    // Use optimizer instead of solver for final solving
    if (opt.check() == sat) {
      model m = opt.get_model();
    }
  }

  std::vector<std::vector<std::vector<int>>> generateSchedule() {
    // Add all constraints
    addOrderingConstraints();
    llvm::errs() << "Ordering constraints added\n";
    addSplitConstraints();
    llvm::errs() << "Split constraints added\n";
    addMemoryConsistencyConstraints();
    llvm::errs() << "Memory consistency constraints added\n";
    addBoundConstraints();
    llvm::errs() << "Bound constraints added\n";
    addRowSumConstraints();
    llvm::errs() << "Column sum constraints added\n";
    addColSumConstraints();
    addOptimizationGoal();

    std::vector<std::vector<std::vector<int>>> result;

    if (s.check() == sat) {
      model m = s.get_model();
      result.resize(numStatements);

      for (int stmtId = 0; stmtId < numStatements; ++stmtId) {
        result[stmtId].resize(numScheduleDimensions);
        for (int row = 0; row < numScheduleDimensions; ++row) {
          result[stmtId][row].resize(numLoopDimensions);
          for (int col = 0; col < numLoopDimensions; ++col) {
            result[stmtId][row][col] =
                m.eval(getScheduleVar(stmtId, row, col)).get_numeral_int();
          }
        }
      }

      // Print the schedule matrices
      llvm::errs() << "Schedule Matrices:\n";
      for (int stmtId = 0; stmtId < numStatements; ++stmtId) {
        llvm::errs() << *statements[stmtId] << "\n";
        llvm::errs() << "S" << stmtId << ":\n";
        for (int row = 0; row < numScheduleDimensions; ++row) {
          llvm::errs() << "  [";
          for (int col = 0; col < numLoopDimensions; ++col) {
            llvm::errs() << result[stmtId][row][col];
            if (col < numLoopDimensions - 1)
              llvm::errs() << ", ";
          }
          llvm::errs() << "]\n";
        }
        llvm::errs() << "\n";
      }
    } else {
      llvm::errs() << "No valid schedule found!\n";
    }

    return result;
  }
};
#endif

// Main function to generate schedule
std::vector<std::vector<std::vector<int>>> generateScheduleFunction(
    affine::AffineForOp &outerFor, const SetVector<Operation *> &statements,
    const SmallVector<Operation *> &blasOps, int scheduleDimensions) {
#ifdef HAVE_Z3
  ScheduleFunctionGenerator generator(outerFor, statements, scheduleDimensions);
  if (blasOps.size() == 3) {
    generator.setBLASOps(blasOps[0], blasOps[1], blasOps[2]);
  } else {
    llvm::errs() << "Not enough BLAS operations provided\n";
  }
  return generator.generateSchedule();
#else
  llvm::errs() << "Z3 not available, cannot generate schedule\n";
  return {};
#endif
}