//===-  PolyhedraSchedule.cpp - Transform to catch mmul Pattern-*- C++ -*-===//
//
// Compigra is under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Implements functions to schedule statements in polyhedra model to catch mmul
// pattern.
//
//===----------------------------------------------------------------------===//

#include "compigra/Support/PolyhedraScheduler.h"
#include "compigra/Support/Utils.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include <numeric>

using namespace mlir;
using namespace mlir::affine;

bool compigra::isSinglePathStore(Value srcVal, affine::AffineStoreOp storeOp,
                                 std::queue<Operation *> &queOps) {
  auto storeVal = storeOp.getValueToStore();
  // check whether storeVal is only generated by srcVal
  if (storeVal == srcVal)
    return true;

  // if srcVal undergoes a series of arithmetic operations with constants,
  // return true
  auto getSingleUser = [&](Value val) {
    auto users = val.getUsers();
    if (users.empty())
      return (Operation *)nullptr;

    // Take the first user as reference
    Operation *firstUser = *users.begin();

    // Ensure all users are the same operation
    for (auto *u : users) {
      if (u != firstUser)
        return (Operation *)nullptr;
    }

    // Check the user has exactly one result
    if (firstUser->getNumResults() != 1)
      return (Operation *)nullptr;

    // Check whether all other operands are constants
    for (auto operand : firstUser->getOperands()) {
      if (operand != val) {
        if (!operand.getDefiningOp() ||
            !isa<arith::ConstantOp>(operand.getDefiningOp()))
          return (Operation *)nullptr;
      }
    }

    return firstUser;
  };

  Operation *singleUser = getSingleUser(srcVal);
  while (singleUser) {
    if (singleUser)
      queOps.push(singleUser);
    if (singleUser->getResult(0) == storeVal)
      return true;
    singleUser = getSingleUser(singleUser->getResult(0));
  }
  return false;
}

void compigra::getAllStatements(
    affine::AffineForOp outerFor,
    SmallVector<SmallVector<Operation *>> &statements) {
  outerFor.walk([&statements](mlir::Operation *op) {
    if (isa<affine::AffineLoadOp, affine::AffineStoreOp>(op)) {
      SmallVector<Operation *> opList;
      opList.push_back(op);
      // insert all arithmatic or constant operations after the load/store
      auto curOp = op->getNextNode();
      while (curOp) {
        // if curOp is a load/store or yield or loop, stop
        if (isa<affine::AffineLoadOp, affine::AffineStoreOp,
                affine::AffineYieldOp, affine::AffineForOp>(curOp)) {
          break;
        }
        opList.push_back(curOp);
        curOp = curOp->getNextNode();
      }

      statements.push_back(opList);
    }
  });
}

int getStatementLevel(AffineForOp rootFor, Operation *op) {
  auto forOp = dyn_cast<AffineForOp>(op->getParentOp());
  int level = 1;
  auto curBlock = forOp->getBlock();
  // Find all enclosing loops and their bounds
  while (curBlock && curBlock != rootFor->getBlock()) {
    level++;
    curBlock =
        curBlock->getParentOp() ? curBlock->getParentOp()->getBlock() : nullptr;
  }
  return level;
}

bool isProducer(Operation *producer, Operation *consumer) {
  for (Value result : producer->getResults()) {
    for (Value operand : consumer->getOperands()) {
      if (result == operand) {
        return true;
      }
    }
  }
  return false;
}

#ifdef HAVE_Z3
using namespace z3;

struct MemoryAccess {
  Operation *op;
  bool isLoad;
  std::vector<Value> indices;
  Value memref;
  int statementId;

  MemoryAccess(Operation *operation, bool load, Value mem, int stmtId)
      : op(operation), isLoad(load), memref(mem), statementId(stmtId) {}
};

struct StatementInfo {
  Operation *op;
  DenseMap<AffineForOp, std::pair<int, int>> bounds;
};

class ScheduleFunctionGenerator {
private:
  context ctx;
  solver s;
  std::vector<Operation *> statements;
  std::vector<MemoryAccess> memoryAccesses;
  AffineForOp rootLoop;
  // Ordered index of the loop iterators
  SmallVector<AffineForOp, 4> loops;
  DenseMap<int, StatementInfo> statementInfos;
  SmallVector<SmallVector<Operation *>> stmts;

  Operation *blasLoad1, *blasLoad2, *blasStore;
  int blasLoad1Id, blasLoad2Id, blasStoreId;

  // Schedule matrix: scheduleMatrix[stmtId][row][col]
  // Each statement has m rows (schedule dimensions) and n=4 columns (3 loops +
  // constant)
  std::map<std::tuple<int, int, int>, expr> scheduleMatrix;
  int numStatements;
  int numScheduleDimensions; // m - number of schedule dimensions (rows)
  int numLoopDimensions;     // n=4 - three loops + constant (columns)

public:
  ScheduleFunctionGenerator(AffineForOp rootLoop,
                            const SmallVector<SmallVector<Operation *>> &stmts,
                            int scheduleDims = 2)
      : rootLoop(rootLoop), stmts(stmts), s(ctx), numStatements(stmts.size()),
        numScheduleDimensions(scheduleDims), numLoopDimensions(4) {
    DenseMap<Operation *, std::pair<int, int>> bounds;
    rootLoop.walk([&](AffineForOp forOp) {
      auto lowerBound = forOp.getLowerBound().getMap();
      auto upperBound = forOp.getUpperBound().getMap();
      int lb = lowerBound.isSingleConstant()
                   ? lowerBound.getSingleConstantResult()
                   : 0;
      int ub = upperBound.isSingleConstant()
                   ? upperBound.getSingleConstantResult()
                   : 10;
      bounds[forOp] = {lb, std::min(ub, 10)};
      loops.insert(loops.begin(), forOp);
    });

    // get the load and store operations and their statement ids
    for (auto opList : stmts) {
      auto op = opList[0];
      StatementInfo info;

      auto curBlock = op->getBlock();
      // Find all enclosing loops and their bounds
      while (curBlock) {
        if (auto forOp = dyn_cast<AffineForOp>(curBlock->getParentOp())) {
          if (bounds.find(forOp) != bounds.end())
            info.bounds[forOp] = bounds[forOp];
        }
        curBlock = curBlock->getParentOp() ? curBlock->getParentOp()->getBlock()
                                           : nullptr;
      }

      info.op = op;
      statementInfos[statements.size()] = info;
      statements.push_back(op);
    }

    // Initialize schedule matrix variables
    initializeScheduleMatrix();

    // Collect memory accesses
    collectMemoryAccesses();
  }

private:
  std::vector<std::vector<int>>
  generateIterationPoints(const std::vector<std::pair<int, int>> &bounds) {
    size_t k = bounds.size();
    std::vector<int> sizes(k);
    size_t total = 1;

    // Compute size of each dimension and total number of rows
    for (size_t i = 0; i < k; ++i) {
      int lower = bounds[i].first;
      int upper = bounds[i].second;
      if (lower > upper) {
        sizes[i] = 1; // column fixed to zero
      } else {
        sizes[i] = upper - lower + 1;
      }
      total *= sizes[i];
    }

    std::vector<std::vector<int>> result;
    result.reserve(total);

    // Generate combinations
    for (size_t idx = 0; idx < total; ++idx) {
      std::vector<int> row(k);
      size_t temp = idx;

      for (size_t j = 0; j < k; ++j) {
        int lower = bounds[j].first;
        int upper = bounds[j].second;

        if (lower > upper) {
          row[j] = 0;
        } else {
          int offset = temp % sizes[j];
          row[j] = lower + offset;
          temp /= sizes[j];
        }
      }
      result.push_back(std::move(row));
    }

    return result;
  }

  // Add lexicographic ordering constraint
  void addLexicographicConstraint(solver &s, const std::vector<expr> &vec1,
                                  const std::vector<expr> &vec2, bool strict) {
    expr result = ctx.bool_val(false);

    for (int i = 0; i < std::min(vec1.size(), vec2.size()); ++i) {
      expr prefixEqual = ctx.bool_val(true);

      // All previous dimensions are equal
      for (int j = 0; j < i; ++j) {
        prefixEqual = prefixEqual && (vec1[j] == vec2[j]);
      }

      // Current dimension: vec1[i] < vec2[i]
      expr currentLess = prefixEqual && (vec1[i] < vec2[i]);
      result = result || currentLess;
    }
    s.add(result == ctx.bool_val(true));
  };

public:
  void setBLASOps(Operation *load1, Operation *load2, Operation *store) {
    blasLoad1 = load1;
    blasLoad2 = load2;
    blasStore = store;

    auto getStatementId = [this](Operation *op) -> std::ptrdiff_t {
      auto it = std::find(statements.begin(), statements.end(), op);
      if (it != statements.end()) {
        return std::distance(statements.begin(), it);
      } else {
        return -1; // Not found
      }
    };

    blasLoad1Id = getStatementId(blasLoad1);
    blasLoad2Id = getStatementId(blasLoad2);
    blasStoreId = getStatementId(blasStore);
  }

  expr getScheduleVar(int stmtId, int row, int col) {
    return scheduleMatrix.at({stmtId, row, col});
  }

  void initializeScheduleMatrix() {
    for (int stmtId = 0; stmtId < numStatements; ++stmtId) {
      for (int row = 0; row < numScheduleDimensions; ++row) {
        for (int col = 0; col < numLoopDimensions; ++col) {
          std::string varName = "theta_" + std::to_string(stmtId) + "_" +
                                std::to_string(row) + "_" + std::to_string(col);
          scheduleMatrix.emplace(std::make_tuple(stmtId, row, col),
                                 ctx.int_const(varName.c_str()));
        }
      }
    }
  }

  void collectMemoryAccesses() {
    for (int i = 0; i < statements.size(); ++i) {
      Operation *op = statements[i];

      if (auto loadOp = dyn_cast<AffineLoadOp>(op)) {
        MemoryAccess access(op, true, loadOp.getMemRef(), i);

        // Extract indices
        for (Value idx : loadOp.getIndices()) {
          access.indices.push_back(idx);
        }
        memoryAccesses.push_back(access);

      } else if (auto storeOp = dyn_cast<AffineStoreOp>(op)) {
        MemoryAccess access(op, false, storeOp.getMemRef(), i);

        // Extract indices
        for (Value idx : storeOp.getIndices()) {
          access.indices.push_back(idx);
        }
        memoryAccesses.push_back(access);
      }
    }
  }

  // Compute schedule vector for a statement at given iteration
  std::vector<expr>
  computeScheduleVector(int stmtId, const std::vector<expr> &iterationVector) {
    std::vector<expr> scheduleVector;

    for (int row = 0; row < numScheduleDimensions; ++row) {
      expr scheduleTime = ctx.int_val(0);

      // For each row: time = sum(theta[stmtId][row][col] *
      // iterationVector[col]) iterationVector should be [i1, i2, i3, 1] to
      // handle constant term
      for (int col = 0; col < numLoopDimensions; ++col) {
        scheduleTime = scheduleTime +
                       getScheduleVar(stmtId, row, col) * iterationVector[col];
      }
      scheduleVector.push_back(scheduleTime);
    }

    return scheduleVector;
  }

  // Get all iteration points for a statement based on its bounds
  std::vector<std::vector<int>> getAllIterationPoints(int stmtId) {
    auto it = statementInfos.find(stmtId);
    if (it == statementInfos.end()) {
      return {};
    }

    const StatementInfo &stmtInfo = it->second;

    // Extract bounds for each loop level
    std::vector<std::pair<int, int>> loopBounds;

    // Need to order the loops by nesting level
    // Assuming the bounds map is ordered by loop nesting depth
    for (auto loop : loops) {
      if (stmtInfo.bounds.find(loop) != stmtInfo.bounds.end()) {
        auto bounds = stmtInfo.bounds.lookup(loop);
        loopBounds.push_back(bounds);
      } else {
        // If the statement is outside this loop, fix the iteration to 0
        loopBounds.push_back({0, -1});
      }
    }

    // Generate all combinations of iteration points
    std::vector<std::vector<int>> iterationPoints =
        generateIterationPoints(loopBounds);

    return iterationPoints;
  }

  // Add universal constraints for all iteration points of two statements
  void addUniversalOrderingConstraint(int stmtId1, int stmtId2,
                                      bool strict = true) {
    auto points1 = getAllIterationPoints(stmtId1);
    auto points2 = getAllIterationPoints(stmtId2);

    // For each valid iteration point in the intersection of domains
    auto commonPoints = getCommonIterationPoints(points1, points2);

    for (const auto &iterPoint : commonPoints) {
      // Add constant term
      std::vector<expr> fullIterPoint;
      for (int val : iterPoint) {
        fullIterPoint.push_back(ctx.int_val(val));
      }

      fullIterPoint.push_back(ctx.int_val(1));

      auto schedule1 = computeScheduleVector(stmtId1, fullIterPoint);
      auto schedule2 = computeScheduleVector(stmtId2, fullIterPoint);

      // Add lexicographic constraint: schedule1 < schedule2 (or <=)
      addLexicographicConstraint(s, schedule1, schedule2, strict);
    }
  }

  // Get common iteration points between two statements
  std::vector<std::vector<int>>
  getCommonIterationPoints(std::vector<std::vector<int>> points1,
                           std::vector<std::vector<int>> points2) {
    if (points1.empty() || points2.empty())
      return {};

    std::vector<std::vector<int>> commonPoints;
    for (const auto &p : points1) {
      if (std::find(points2.begin(), points2.end(), p) != points2.end()) {
        commonPoints.push_back(p);
      }
    }
    return commonPoints;
  }

  // Example usage for your specific constraint: S0 < S1 < S2 < Sk
  void addOrderingConstraints() {
    // keep iterative order
    for (auto [sId, info] : statementInfos) {
      for (auto [forOp, bounds] : info.bounds) {
        if (bounds.first > bounds.second)
          continue;
        auto ivId = std::distance(loops.begin(),
                                  std::find(loops.begin(), loops.end(), forOp));
        s.add(getScheduleVar(sId, 1 + 2 * ivId, ivId) == 1);
      }
      int loopLevel = getStatementLevel(rootLoop, info.op);
      for (auto dim = 2; dim < loopLevel * 2; dim += 2)
        s.add(getScheduleVar(sId, dim, numLoopDimensions - 1) == 0);
    }
    addUniversalOrderingConstraint(blasLoad1Id, blasLoad2Id, false);
    addUniversalOrderingConstraint(blasLoad2Id, blasStoreId, true);

    // Si < Sk for i ∈ {0,1,2}, k ≥ 3
    for (size_t i = 0; i < std::min(statements.size(), size_t(3)); ++i) {
      if (i == blasLoad1Id || i == blasLoad2Id || i == blasStoreId)
        continue;
      addUniversalOrderingConstraint(blasStoreId, i, true);
    }

    for (size_t i = 0; i < std::min(statements.size(), size_t(3)); ++i) {
      if (i == blasLoad1Id || i == blasLoad2Id || i == blasStoreId)
        continue;
      addUniversalOrderingConstraint(blasStoreId, i, true);
    }
  }

  void addSplitConstraints() {
    // For non-BLAS statements, Sk should be completely split to current scope
    int lastD = numLoopDimensions - 1;
    for (int k = 0; k < statements.size(); ++k) {
      if (k == blasLoad1Id || k == blasLoad2Id || k == blasStoreId)
        s.add(getScheduleVar(k, 0, lastD) == 0);
      else
        s.add(getScheduleVar(k, 0, lastD) == 1);
    }
  }

  void addMemoryConsistencyConstraints() {
    // For each pair of memory accesses to the same address
    for (int i = 0; i < memoryAccesses.size(); ++i) {
      for (int j = i + 1; j < memoryAccesses.size(); ++j) {
        const MemoryAccess &access1 = memoryAccesses[i];
        const MemoryAccess &access2 = memoryAccesses[j];

        // Check if accessing the same memory location
        if (access1.memref == access2.memref &&
            accessesSameLocation(access1, access2)) {
          // Add dependence constraint
          if (createsDependence(access1, access2)) {
            addUniversalOrderingConstraint(access1.statementId,
                                           access2.statementId, true);
          }
        }
      }
    }
  }

  bool accessesSameLocation(const MemoryAccess &acc1,
                            const MemoryAccess &acc2) {
    // Simplified check - in practice, you'd need more sophisticated analysis
    return acc1.memref == acc2.memref &&
           acc1.indices.size() == acc2.indices.size();
  }

  bool createsDependence(const MemoryAccess &acc1, const MemoryAccess &acc2) {
    // True dependence: Read after Write
    // Anti-dependence: Write after Read
    // Output dependence: Write after Write
    return (!acc1.isLoad && acc2.isLoad) || // RAW
           (acc1.isLoad && !acc2.isLoad) || // WAR
           (!acc1.isLoad && !acc2.isLoad);  // WAW
  }

  void addBoundConstraints() {
    // Add reasonable bounds to avoid unbounded solutions
    for (int stmtId = 0; stmtId < numStatements; ++stmtId) {
      for (int row = 0; row < numScheduleDimensions; ++row) {
        for (int col = 0; col < numLoopDimensions; ++col) {
          s.add(getScheduleVar(stmtId, row, col) >= 0);
          if (col < numLoopDimensions - 1)
            s.add(getScheduleVar(stmtId, row, col) <= 1);
        }
      }
    }
  }

  void addRowSumConstraints() {
    // Ensure that for each statement, the sum of coefficients in each row is
    // at least 1
    for (int stmtId = 0; stmtId < numStatements; ++stmtId) {
      for (int col = 0; col < numLoopDimensions - 1; ++col) {
        expr rowSum = ctx.int_val(0);
        for (int row = 0; row < numScheduleDimensions; ++row) {
          rowSum = rowSum + getScheduleVar(stmtId, row, col);
        }
        s.add(rowSum <= 1);
      }
    }
  }

  void addColSumConstraints() {
    // Ensure that for each statement, the sum of coefficients in each row is
    // at least 1
    for (int stmtId = 0; stmtId < numStatements; ++stmtId) {
      for (int row = 1; row < numScheduleDimensions; row += 2) {
        expr colSum = ctx.int_val(0);
        for (int col = 0; col < numLoopDimensions; ++col) {
          colSum = colSum + getScheduleVar(stmtId, row, col);
        }
        s.add(colSum <= 1);
      }
    }
  }

  void addOptimizationGoal() {
    // Minimize the sum of absolute values of coefficients in even rows (rows
    // % 2 == 0)
    expr objective = ctx.int_val(0);

    for (int stmtId = 0; stmtId < numStatements; ++stmtId) {
      for (int row = 0; row < numScheduleDimensions; row += 2) {
        for (int col = 0; col < numLoopDimensions; ++col) {
          expr coeff = getScheduleVar(stmtId, row, col);

          // Add to objective
          objective = objective + coeff;
        }
      }
    }

    // Create optimizer and transfer constraints
    optimize opt(ctx);
    for (auto const &assertion : s.assertions()) {
      opt.add(assertion);
    }
    opt.minimize(objective);

    // Use optimizer instead of solver for final solving
    if (opt.check() == sat) {
      model m = opt.get_model();
    }
  }

  void addDominanceConstraints() {
    for (int i = 0; i < stmts.size(); i++) {
      for (int j = 0; j < stmts.size(); j++) {
        if (i == j)
          continue;
        auto group1 = stmts[i];
        auto group2 = stmts[j];
        // if one of the operations is the producer of a value consumed by one
        // of the operations in the other group, then add dominance constraint
        bool existsDependency = false;
        for (auto op1 : group1)
          for (auto op2 : group2) {
            if (isProducer(op1, op2)) {
              existsDependency = true;
              break;
            }
            if (existsDependency)
              break;
          }

        if (existsDependency)
          addUniversalOrderingConstraint(i, j, true);
      }
    }
  }

  std::vector<std::vector<std::vector<int>>> generateSchedule() {
    // Add all constraints
    addOrderingConstraints();
    addSplitConstraints();
    addMemoryConsistencyConstraints();
    addBoundConstraints();
    addRowSumConstraints();
    addColSumConstraints();
    addOptimizationGoal();
    addDominanceConstraints();

    std::vector<std::vector<std::vector<int>>> result;

    if (s.check() == sat) {
      model m = s.get_model();
      result.resize(numStatements);

      for (int stmtId = 0; stmtId < numStatements; ++stmtId) {
        result[stmtId].resize(numScheduleDimensions);
        for (int row = 0; row < numScheduleDimensions; ++row) {
          result[stmtId][row].resize(numLoopDimensions);
          for (int col = 0; col < numLoopDimensions; ++col) {
            result[stmtId][row][col] =
                m.eval(getScheduleVar(stmtId, row, col)).get_numeral_int();
          }
        }
      }

      // Print the schedule matrices
      llvm::errs() << "Schedule Matrices:\n";
      for (int stmtId = 0; stmtId < numStatements; ++stmtId) {
        llvm::errs() << *statements[stmtId] << "\n";
        llvm::errs() << "S" << stmtId << ":\n";
        for (int row = 0; row < numScheduleDimensions; ++row) {
          llvm::errs() << "  [";
          for (int col = 0; col < numLoopDimensions; ++col) {
            llvm::errs() << result[stmtId][row][col];
            if (col < numLoopDimensions - 1)
              llvm::errs() << ", ";
          }
          llvm::errs() << "]\n";
        }
        llvm::errs() << "\n";
      }
    } else {
      llvm::errs() << "No valid schedule found!\n";
    }

    return result;
  }
};
#endif

// Main function to generate schedule
std::vector<std::vector<std::vector<int>>> compigra::generateScheduleFunction(
    affine::AffineForOp &outerFor,
    const SmallVector<SmallVector<Operation *>> &statements,
    const SmallVector<Operation *> &blasOps, int scheduleDimensions) {
#ifdef HAVE_Z3
  ScheduleFunctionGenerator generator(outerFor, statements, scheduleDimensions);
  if (blasOps.size() == 3) {
    generator.setBLASOps(blasOps[0], blasOps[1], blasOps[2]);
  } else {
    llvm::errs() << "Not enough BLAS operations provided\n";
    return {};
  }
  return generator.generateSchedule();
#else
  llvm::errs() << "Z3 not available, cannot generate schedule\n";
  return {};
#endif
}

// Function to create a new AffineForOp, copying bounds from sibling loops when
// available
AffineForOp
createLoopBasedOnSibling(const std::vector<int> &targetKey,
                         const std::map<std::vector<int>, AffineForOp> &loopMap,
                         OpBuilder &builder, Location loc) {

  // Try to find an existing sibling loop to copy bounds from
  AffineForOp templateLoop = nullptr;

  if (targetKey.size() > 0) {
    std::vector<int> siblingKey;
    for (auto k : targetKey)
      siblingKey.push_back(0);
    auto it = loopMap.find(siblingKey);
    templateLoop = (it != loopMap.end()) ? it->second : nullptr;
  }

  if (!templateLoop)
    // No template found, return nullptr
    return nullptr;

  // Copy bounds and step from the template loop
  auto lowerBound = templateLoop.getLowerBoundMap();
  auto upperBound = templateLoop.getUpperBoundMap();
  auto step = templateLoop.getStep();

  // Copy operands as well
  auto lowerBoundOperands = templateLoop.getLowerBoundOperands();
  auto upperBoundOperands = templateLoop.getUpperBoundOperands();

  AffineForOp newLoop =
      builder.create<AffineForOp>(loc,
                                  lowerBoundOperands, // Lower bound operands
                                  lowerBound,         // Lower bound map
                                  upperBoundOperands, // Upper bound operands
                                  upperBound,         // Upper bound map
                                  step                // Step
      );

  return newLoop;
}

LogicalResult insertLoopByKey(const std::vector<int> &targetKey,
                              std::map<std::vector<int>, AffineForOp> &loopMap,
                              OpBuilder &builder) {

  // If key already exists, return success
  if (loopMap.find(targetKey) != loopMap.end()) {
    return success();
  }

  // Helper function to create missing parent hierarchy
  std::function<LogicalResult(const std::vector<int> &)> ensureParentExists =
      [&](const std::vector<int> &key) -> LogicalResult {
    if (loopMap.find(key) != loopMap.end()) {
      return success();
    }

    // Ensure parent exists first (if not root level)
    if (key.size() > 1) {
      std::vector<int> parentKey(key.begin(), key.end() - 1);
      if (failed(ensureParentExists(parentKey))) {
        return failure();
      }
    }

    // Find insertion point
    int targetIndex = key.back();
    AffineForOp insertAfterLoop = nullptr;

    // Look for the highest indexed existing sibling less than targetIndex
    for (int i = targetIndex - 1; i >= 0; i--) {
      std::vector<int> siblingKey = key;
      siblingKey.back() = i;

      auto it = loopMap.find(siblingKey);
      if (it != loopMap.end()) {
        insertAfterLoop = it->second;
        break;
      }
    }

    if (!insertAfterLoop && key.size() == 1) {
      // Root level and no existing root found - should not happen since {0}
      // should exist
      return failure();
    }

    // Set insertion point
    Location loc = builder.getUnknownLoc();
    if (insertAfterLoop) {
      builder.setInsertionPointAfter(insertAfterLoop);
    } else {
      // No existing sibling found, insert at beginning of parent
      std::vector<int> parentKey(key.begin(), key.end() - 1);
      AffineForOp parentLoop = loopMap[parentKey];
      builder.setInsertionPointToStart(parentLoop.getBody());
    }

    // Create the new loop
    AffineForOp newLoop = createLoopBasedOnSibling(key, loopMap, builder, loc);
    loopMap[key] = newLoop;
    if (!newLoop)
      return failure();

    return success();
  };

  // Create the target key (this will recursively create all missing parents)
  return ensureParentExists(targetKey);
}

// Helper function to compare two priority vectors lexicographically
bool isLexicographicallySmaller(const std::vector<int> &a,
                                const std::vector<int> &b) {
  return std::lexicographical_compare(a.begin(), a.end(), b.begin(), b.end());
}

void insertToAffineFor(affine::AffineForOp loop,
                       SmallVector<Operation *> insertOps,
                       std::map<Operation *, std::vector<int>> stmtPriority) {

  // Handle empty case
  if (insertOps.empty()) {
    return;
  }

  // Get the priority for the first operation (all operations are treated as
  // having the same priority)
  std::vector<int> insertPriority;
  bool hasPriority = false;

  // Find the first operation that has a priority
  for (Operation *op : insertOps) {
    if (stmtPriority.find(op) != stmtPriority.end()) {
      insertPriority = stmtPriority[op];
      hasPriority = true;
      break;
    }
  }

  // If no operation has a priority, insert all at the end maintaining their
  // order
  if (!hasPriority) {
    Operation *terminator = loop.getBody()->getTerminator();
    for (Operation *op : insertOps) {
      op->moveBefore(terminator);
    }
    return;
  }

  // Collect all operations in the same loop that have priorities
  std::vector<std::pair<Operation *, std::vector<int>>> opsInLoop;

  // Walk through all operations in the loop body
  for (auto &op : loop.getOps()) {
    if (&op == loop.getBody()->getTerminator() && // Skip terminator
        stmtPriority.find(&op) == stmtPriority.end())
      continue;

    bool isInInsertOps = false;
    for (Operation *insertOp : insertOps) {
      if (&op == insertOp) {
        isInInsertOps = true;
        break;
      }
    }

    if (!isInInsertOps) {
      opsInLoop.push_back({&op, stmtPriority[&op]});
    }
  }

  // Sort operations by their lexicographical priority
  std::sort(opsInLoop.begin(), opsInLoop.end(),
            [](const auto &a, const auto &b) {
              return isLexicographicallySmaller(a.second, b.second);
            });

  // Find the correct insertion position
  Operation *insertBefore = nullptr;

  for (const auto &pair : opsInLoop) {
    Operation *op = pair.first;
    const std::vector<int> &priority = pair.second;

    // If the current operation has a higher priority (lexicographically larger)
    // than our insert operations, we should insert before it
    if (isLexicographicallySmaller(insertPriority, priority)) {
      insertBefore = op;
      break;
    }
  }

  // Insert all operations at the determined position, maintaining their order
  if (insertBefore) {
    // Insert in reverse order so the final order matches insertOps
    for (Operation *op : insertOps) {
      op->moveBefore(insertBefore);
    }
  } else {
    // Insert before the terminator (at the end of meaningful operations)
    Operation *terminator = loop.getBody()->getTerminator();
    for (Operation *op : insertOps)
      op->moveBefore(terminator);
  }
}

LogicalResult compigra::reorderStatements(
    affine::AffineForOp outerFor,
    const std::vector<std::vector<std::vector<int>>> &scheduleMatrix,
    const SmallVector<SmallVector<Operation *>> &statements,
    OpBuilder &builder) {
  if (scheduleMatrix.empty() || scheduleMatrix[0].empty())
    return success();
  std::map<std::vector<int>, AffineForOp> loopMap;
  std::map<Operation *, std::vector<int>> stmtPriority;

  struct LoopInfo {
    AffineForOp loop;
    std::vector<int> key;
  };

  // write existing loops into map
  std::vector<LoopInfo> stack;
  stack.push_back({outerFor, {0}});

  while (!stack.empty()) {
    LoopInfo current = stack.back();
    stack.pop_back();

    // Add current loop to map
    loopMap[current.key] = current.loop;

    // Collect direct child loops
    std::vector<AffineForOp> childLoops;

    current.loop.getBody()->walk([&](AffineForOp childLoop) {
      // Only collect direct children
      if (childLoop.getOperation()->getParentOp() ==
          current.loop.getOperation()) {
        childLoops.push_back(childLoop);
      }
    });

    // Add children to stack with appropriate keys
    for (int i = 0; i < childLoops.size(); i++) {
      std::vector<int> childKey = current.key;
      childKey.push_back(i);
      stack.push_back({childLoops[i], childKey});
    }
  }

  auto ivDim = scheduleMatrix[0][0].size();
  // create new loops according to scheduleMatrix
  for (int i = 0; i < scheduleMatrix.size(); i++) {
    auto stmt = statements[i][0];
    auto scheduleM = scheduleMatrix[i];

    auto loopLevels = getStatementLevel(outerFor, stmt);
    std::vector<int> priority;
    for (size_t row = 2 * loopLevels; row < scheduleM.size(); ++row) {
      priority.push_back(scheduleM[row][ivDim - 1]);
    }
    for (auto s : statements[i])
      stmtPriority[s] = priority;

    std::vector<int> iterKey;
    for (auto level = 0; level < loopLevels; level++) {
      iterKey.push_back(scheduleMatrix[i][2 * level][ivDim - 1]);
    }

    if (loopMap.find(iterKey) == loopMap.end()) {
      if (failed(insertLoopByKey(iterKey, loopMap, builder)))
        return failure();
    }
    // create new loops

    auto loop = loopMap[iterKey];
    // move the statement into the scope
    insertToAffineFor(loop, statements[i], stmtPriority);

    for (int bit = 1; bit <= iterKey.size(); bit++) {
      std::vector<int> loopHierarchy(iterKey.begin(), iterKey.begin() + bit);
      std::vector<int> origHierachy(bit, 0);
      // if loopHierarchy equals to origHierachy, no need to replace iv
      if (loopHierarchy == origHierachy)
        continue;

      auto origFor = loopMap[origHierachy];
      auto nestFor = loopMap[loopHierarchy];
      for (auto s : statements[i]) {
        // replace the operations' iv with the new loop's iv
        for (auto operand : s->getOperands())
          if (operand == origFor.getInductionVar())
            s->replaceUsesOfWith(operand, nestFor.getInductionVar());
      }
    }
  }

  return success();
}
